version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - es_network

  rag_system:
    build: .
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - OPENAI_API_KEY=  "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"
      - HUGGINGFACEHUB_API_TOKEN=  "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"
    depends_on:
      - elasticsearch 
    ports:
      - "7860:7860"
    networks:
      - es_network

networks:
  es_network:
    driver: bridge
